"""endpoint_centric_observability

Revision ID: b2459ae79c17
Revises: 11ae282f994f
Create Date: 2026-06-16 13:46:27.236163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2459ae79c17'
down_revision: Union[str, None] = '11ae282f994f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_endpoints',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_path', sa.String(length=255), nullable=False),
    sa.Column('request_method', sa.String(length=16), nullable=False),
    sa.Column('feature', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('base_url', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'description')
    op.drop_column('applications', 'base_url')
    op.drop_table('application_endpoints')
    # ### end Alembic commands ###
